name: gemcon
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - numpy=1.22
  - scipy=1.7
  - pandas=1.3
  - matplotlib=3.5
  - scikit-learn=1.6
  - statsmodels=0.14
  - numba=0.58
  - llvmlite=0.41
  - h5py
  - sympy=1.12
  - mpmath=1.3
  - networkx
  - patsy
  - seaborn
  - pillow
  - fonttools
  - kiwisolver
  - cycler
  - contourpy
  - pyparsing
  - unicodedata2
  - munkres
  - tqdm
  - rich
  - pygments
  - markdown-it-py
  - mdurl
  - joblib
  - threadpoolctl
  - packaging
  - python-dateutil
  - pytz
  - tzdata
  - six
  - typing_extensions
  - typing-inspection
  - importlib_metadata
  - importlib_resources
  - zipp
  - cached_property
  - appdirs
  - natsort
  - legacy-api-wrap
  - depinfo
  - exceptiongroup
  - annotated-types
  - session-info2
  - ruamel.yaml
  - ruamel.yaml.clib
  - future
  - httpx
  - httpcore
  - h11
  - h2
  - hpack
  - hyperframe
  - anyio
  - sniffio
  - idna
  - pydantic
  - pydantic-core
  - python-libsbml
  - swiglpk
  - gmpy2
  - array-api-compat
  - pynndescent
  - beautifulsoup4
  - lxml
  - pip
  - pip:
      - anndata==0.10.5.post1
      - scanpy==1.9.6
      - celltypist==1.7.1
      - umap-learn==0.5.7
      - leidenalg==0.11.0
      - igraph==1.0.0
      - session_info==1.0.1
      - cobra==0.28.0
      - cobamp
      - corda==0.5.1
      - riptide
      - troppo
      - optlang==1.5.2
      - git+https://github.com/ToruOkadaOi/geckopy.git@545d35721a0d47cb3c95f081e2dec1cf01dfa899
      - boolean.py==4.0
      - click==8.3.2
      - dill==0.4.1
      - diskcache==5.6.3
      - et_xmlfile==2.0.0
      - openpyxl==3.1.5
      - indexed==1.2.1
      - multiprocess==0.70.19
      - pathos==0.2.9
      - pox==0.3.7
      - ppft==1.7.8
      - stdlib-list==0.12.0
      - texttable==1.7.0
      - charset-normalizer==3.4.7
      - symengine==0.14.1
      - requests==2.33.1
      - urllib3==2.6.3
      - python-json-logger
      - aiohttp
      - pyyaml
      - loompy
      - typer
      - cplex==22.1.2.1
      - docplex